main: np_simple.cpp np_single_proc.cpp np_multi_proc.cpp user.cpp user_multi.cpp numberpipe.cpp utils.cpp
	 g++ np_simple.cpp -o np_simple
	 g++ np_single_proc.cpp -o np_single_proc
	 g++ np_multi_proc.cpp -lrt -o np_multi_proc
